version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: libsysmgmt
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
      
  backend:
    build: ./backend
    restart: on-failure
    ports:
      - 8000:8000
    command: [
	    "sh", 
	    "-c", 
	    "php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8000"
	  ]
      
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 4200:4200
    environment:
      NG_APP_HOST_API: backend:8000

volumes:
  mysql_data:
